#!/bin/bash

BINDDIR="${BINDDIR:-/opt/aur-builder}"
CONTAINER="${CONTAINER:-repo}"
REPO="${REPO:-propter}"
PKGDEST="${PKGDEST:-${BINDDIR}/repo/x86_64}"
TIMEOUT="${TIMEOUT:-60}"

source "${BINDDIR}/creds"

# Change to repo
cd "$PKGDEST"

# Grab new packages if any
turbolift -I download -s . -c "$CONTAINER" --dl-sync

# *Prune list*
# TODO: Write this
# Make array of packages
# Split name/version
# vercmp list to get all-but-$n list
#   Delete difference locally
#   Delete difference via turbolift
#   Alternately nuke container and re-tsync

# Update databases
repo-add -n -s "${REPO}.db.tar.gz" *.xz
repo-add -n -f -s "${REPO}.files.tar.gz" *.xz

# Push back up
turbolift -I tsync -s . -c "$CONTAINER" --cdn-enable
